import heroImg from '../assets/images/hero_fashion_editorial_1790774634384.jpg';
import avatarImg from '../assets/images/avatar_digital_twin_1790774648245.jpg';
import outfitSmartImg from '../assets/images/outfit_minimalist_smart_1790774665034.jpg';
import outfitStreetImg from '../assets/images/outfit_streetwear_urban_1790774681092.jpg';
import samplePortraitImg from '../assets/images/sample_reference_portrait_1790777868145.jpg';
import samplePortraitMaleImg from '../assets/images/sample_portrait_male_1790778303678.jpg';
import { OutfitLook, ProductItem, UserProfile } from '../types';

export const ASSET_IMAGES = {
  hero: heroImg,
  avatar: avatarImg,
  outfitSmart: outfitSmartImg,
  outfitStreet: outfitStreetImg,
  samplePortrait: samplePortraitImg,
  samplePortraitMale: samplePortraitMaleImg,
};

export const SAMPLE_PROFILE: UserProfile = {
  id: 'ft_user_default_01',
  displayName: 'Elena Vance',
  ageRange: '25-34',
  units: 'metric',
  measurements: {
    height: 176,
    shoulderWidth: 42,
    chest: 90,
    waist: 72,
    hip: 96,
    armLength: 59,
    inseam: 81,
    weight: 64,
  },
  appearance: {
    skinTone: '#E0B594',
    hairStyle: 'Textured Bob',
    hairColor: '#2B1E16',
    referencePhotoUrl: samplePortraitImg,
    avatarProvider: 'neural-photomap',
    facialMorphology: {
      faceShape: 'oval',
      jawWidth: 0.95,
      chinPointiness: 1.08,
      cheekboneProminence: 1.15,
      noseBridgeElevation: 1.06,
      noseWidth: 0.94,
      lipFullness: 1.12,
      eyeSpacing: 1.02,
      detectedSkinTone: '#E0B594',
      detectedHairStyle: 'Textured Bob',
      detectedHairColor: '#2B1E16',
      confidenceScore: 97.4,
    },
  },
  preferences: {
    styles: ['Minimalist', 'Smart Casual', 'Streetwear'],
    favoriteColors: ['#244D3C', '#20211F', '#F8F7F4', '#A6B6A3', '#D5C4A1'],
    categories: ['Outerwear', 'Tops', 'Trousers', 'Footwear'],
    budgetTier: 'contemporary',
  },
  createdAt: '2026-03-15T10:00:00.000Z',
  updatedAt: '2026-03-28T14:30:00.000Z',
};

export const MOCK_OUTFITS: OutfitLook[] = [
  {
    id: 'outfit-01',
    name: 'Architectural Forest Ensemble',
    occasion: 'Office',
    style: 'Minimalist',
    budgetTier: 'contemporary',
    explanation:
      'Curated for your 176cm athletic silhouette with broad shoulders. The structured wool overcoat provides elongated vertical line harmony, while the relaxed tapered trousers balance hip and shoulder proportions.',
    imageUrl: outfitSmartImg,
    silhouetteMatchScore: 97,
    matchReason: 'Shoulder-to-waist ratio calculated at 1.25 aligns seamlessly with structured double-face wool tailoring.',
    totalPrice: 685,
    items: [
      {
        id: 'item-01',
        name: 'Structured Double-Face Wool Overcoat',
        category: 'Outerwear',
        brand: 'Lemaire Atelier',
        price: 380,
        currency: '$',
        imageUrl: outfitSmartImg,
        retailerUrl: 'https://example.com/lemaire/overcoat',
        color: 'Deep Forest',
        fitDescription: 'Relaxed drop-shoulder cut providing room for shoulder width 42cm.',
      },
      {
        id: 'item-02',
        name: 'Pure Merino Mock-Neck Knit',
        category: 'Tops',
        brand: 'COS Studio',
        price: 115,
        currency: '$',
        imageUrl: outfitSmartImg,
        retailerUrl: 'https://example.com/cos/merino-knit',
        color: 'Ivory Cream',
        fitDescription: 'Tailored regular fit that hugs 90cm chest without tension.',
      },
      {
        id: 'item-03',
        name: 'Pleated Wide-Leg Wool Trousers',
        category: 'Bottoms',
        brand: 'Arket Minimal',
        price: 140,
        currency: '$',
        imageUrl: outfitSmartImg,
        retailerUrl: 'https://example.com/arket/pleated-trouser',
        color: 'Oatmeal Taupe',
        fitDescription: 'High-waisted with 81cm inseam matching your natural leg line.',
      },
      {
        id: 'item-04',
        name: 'Square-Toe Calfskin Chelsea Boot',
        category: 'Footwear',
        brand: 'Totême Form',
        price: 250,
        currency: '$',
        imageUrl: outfitSmartImg,
        retailerUrl: 'https://example.com/toteme/chelsea-boot',
        color: 'Charcoal Black',
        fitDescription: 'Clean elongated profile anchoring wide-leg hems.',
      },
    ],
  },
  {
    id: 'outfit-02',
    name: 'Sage Urban Heavyweight Silhouette',
    occasion: 'Casual Outing',
    style: 'Streetwear',
    budgetTier: 'contemporary',
    explanation:
      'Engineered for relaxed everyday movement. The heavyweight boxy bomber creates modern volumetric balance across the upper torso, anchored by selvedge denim with tailored break.',
    imageUrl: outfitStreetImg,
    silhouetteMatchScore: 94,
    matchReason: 'Boxy jacket length hits precisely at the 72cm waistline to enhance proportional leg length.',
    totalPrice: 490,
    items: [
      {
        id: 'item-05',
        name: 'Washed Heavy Cotton Bomber Jacket',
        category: 'Outerwear',
        brand: 'Studio Nicholson',
        price: 260,
        currency: '$',
        imageUrl: outfitStreetImg,
        retailerUrl: 'https://example.com/nicholson/bomber',
        color: 'Muted Sage',
        fitDescription: 'Boxy cropped torso with ribbed hem sitting naturally above hips.',
      },
      {
        id: 'item-06',
        name: 'Heavyweight Supima Cotton Tee',
        category: 'Tops',
        brand: 'Auralee Tokyo',
        price: 75,
        currency: '$',
        imageUrl: outfitStreetImg,
        retailerUrl: 'https://example.com/auralee/tee',
        color: 'Chalk White',
        fitDescription: 'Structured 280gsm knit keeping clean geometric drape.',
      },
      {
        id: 'item-07',
        name: 'Raw Japanese Selvedge Straight Jean',
        category: 'Bottoms',
        brand: 'Acne Studios',
        price: 155,
        currency: '$',
        imageUrl: outfitStreetImg,
        retailerUrl: 'https://example.com/acne/selvedge-straight',
        color: 'Indigo Rinse',
        fitDescription: 'Mid-rise straight cut measured for 96cm hip breadth.',
      },
    ],
  },
  {
    id: 'outfit-03',
    name: 'Monochrome Evening Gala Tailoring',
    occasion: 'Party',
    style: 'Formal',
    budgetTier: 'luxury',
    explanation:
      'A sharp, sculptured formal silhouette in midnight charcoal with silk-satin lapels. Accentuates upright posture and clean architectural shoulder lines.',
    imageUrl: heroImg,
    silhouetteMatchScore: 96,
    matchReason: 'Precision shoulder tailoring crafted to sit clean with 42cm shoulder breadth.',
    totalPrice: 1120,
    items: [
      {
        id: 'item-08',
        name: 'Sculpted Peak-Lapel Evening Tuxedo Jacket',
        category: 'Outerwear',
        brand: 'Ralph Lauren Black Label',
        price: 720,
        currency: '$',
        imageUrl: heroImg,
        retailerUrl: 'https://example.com/ralphlauren/tuxedo',
        color: 'Midnight Charcoal',
        fitDescription: 'Single-button closure with structured canvas chest piece.',
      },
      {
        id: 'item-09',
        name: 'Silk Georgette Band-Collar Shirt',
        category: 'Tops',
        brand: 'Lemaire Night',
        price: 240,
        currency: '$',
        imageUrl: heroImg,
        retailerUrl: 'https://example.com/lemaire/silk-shirt',
        color: 'Raw Silk Off-White',
        fitDescription: 'Fluid drape with 59cm sleeve length.',
      },
      {
        id: 'item-10',
        name: 'High-Rise Barathea Wool Evening Trousers',
        category: 'Bottoms',
        brand: 'Savitri Bespoke',
        price: 160,
        currency: '$',
        imageUrl: heroImg,
        retailerUrl: 'https://example.com/savitri/trousers',
        color: 'Midnight Charcoal',
        fitDescription: 'Side adjusters tailored exactly to 72cm waist.',
      },
    ],
  },
  {
    id: 'outfit-04',
    name: 'Textured Linen Horizon Set',
    occasion: 'Travel',
    style: 'Smart Casual',
    budgetTier: 'contemporary',
    explanation:
      'Breathable garment-dyed European linen layers designed for effortless travel transition. Natural creases lend character while keeping refined geometric structure.',
    imageUrl: outfitSmartImg,
    silhouetteMatchScore: 91,
    matchReason: 'Unconstructed shoulders and relaxed armscye provide complete freedom of motion.',
    totalPrice: 420,
    items: [
      {
        id: 'item-11',
        name: 'Unstructured Garment-Dyed Linen Overshirt',
        category: 'Outerwear',
        brand: 'Margaret Howell',
        price: 210,
        currency: '$',
        imageUrl: outfitSmartImg,
        retailerUrl: 'https://example.com/howell/linen-overshirt',
        color: 'Olive Sage',
        fitDescription: 'Dual chest patch pockets and straight hem.',
      },
      {
        id: 'item-12',
        name: 'Drawstring Elasticated Linen Chino',
        category: 'Bottoms',
        brand: 'Officine Générale',
        price: 150,
        currency: '$',
        imageUrl: outfitSmartImg,
        retailerUrl: 'https://example.com/officine/linen-chino',
        color: 'Natural Ecru',
        fitDescription: 'Internal drawstring waist with relaxed thigh room.',
      },
      {
        id: 'item-13',
        name: 'Woven Calfskin Espadrille Loafer',
        category: 'Footwear',
        brand: 'Castañer Homme',
        price: 60,
        currency: '$',
        imageUrl: outfitSmartImg,
        retailerUrl: 'https://example.com/castaner/loafer',
        color: 'Deep Moss',
        fitDescription: 'Flexible vulcanized jute sole with leather insole.',
      },
    ],
  },
  {
    id: 'outfit-05',
    name: 'Modern Contemporary Kurta & Tailored Trousers',
    occasion: 'Wedding',
    style: 'Ethnic',
    budgetTier: 'contemporary',
    explanation:
      'Contemporary ceremonial styling fusing pure raw silk minimal asymmetrical kurta with crisp European tailored trousers. Sophisticated, refined, and culturally timeless.',
    imageUrl: heroImg,
    silhouetteMatchScore: 95,
    matchReason: 'Vertical asymmetrical placket accentuates height and lean torso proportion.',
    totalPrice: 530,
    items: [
      {
        id: 'item-14',
        name: 'Asymmetrical Raw Matka Silk Kurta',
        category: 'Tops',
        brand: 'Antar-Agni Studio',
        price: 280,
        currency: '$',
        imageUrl: heroImg,
        retailerUrl: 'https://example.com/antaragni/kurta',
        color: 'Forest Olive',
        fitDescription: 'Geometric wrap front with concealed horn fasteners.',
      },
      {
        id: 'item-15',
        name: 'Tapered Wool Barathea Churidar-Pants',
        category: 'Bottoms',
        brand: 'Raw Mango Atelier',
        price: 160,
        currency: '$',
        imageUrl: heroImg,
        retailerUrl: 'https://example.com/rawmango/trousers',
        color: 'Charcoal Black',
        fitDescription: 'Tailored ankle taper with hidden ankle zipper.',
      },
      {
        id: 'item-16',
        name: 'Handcrafted Leather Mojari Slides',
        category: 'Footwear',
        brand: 'Needledust Form',
        price: 90,
        currency: '$',
        imageUrl: heroImg,
        retailerUrl: 'https://example.com/needledust/mojari',
        color: 'Antiqued Burnished Brown',
        fitDescription: 'Cushioned memory-foam footbed with vegetable tan leather.',
      },
    ],
  },
];

export const MOCK_PRODUCTS: ProductItem[] = [
  {
    id: 'prod-01',
    name: 'Structured Double-Face Wool Overcoat',
    category: 'Outerwear',
    style: 'Minimalist',
    price: 380,
    retailer: 'Lemaire Atelier',
    imageUrl: outfitSmartImg,
    productUrl: 'https://example.com/lemaire-wool-overcoat',
    isNewArrival: true,
  },
  {
    id: 'prod-02',
    name: 'Washed Heavy Cotton Bomber Jacket',
    category: 'Outerwear',
    style: 'Streetwear',
    price: 260,
    retailer: 'Studio Nicholson',
    imageUrl: outfitStreetImg,
    productUrl: 'https://example.com/studio-nicholson-bomber',
    isNewArrival: true,
  },
  {
    id: 'prod-03',
    name: 'Pure Merino Mock-Neck Knit',
    category: 'Tops',
    style: 'Minimalist',
    price: 115,
    retailer: 'COS Studio',
    imageUrl: outfitSmartImg,
    productUrl: 'https://example.com/cos-merino-knit',
  },
  {
    id: 'prod-04',
    name: 'Japanese Selvedge Straight Denim',
    category: 'Trousers',
    style: 'Streetwear',
    price: 155,
    retailer: 'Acne Studios',
    imageUrl: outfitStreetImg,
    productUrl: 'https://example.com/acne-selvedge-denim',
  },
  {
    id: 'prod-05',
    name: 'Pleated Wide-Leg Wool Trousers',
    category: 'Trousers',
    style: 'Smart Casual',
    price: 140,
    retailer: 'Arket Minimal',
    imageUrl: outfitSmartImg,
    productUrl: 'https://example.com/arket-pleated-trouser',
  },
  {
    id: 'prod-06',
    name: 'Peak-Lapel Tuxedo Blazer',
    category: 'Outerwear',
    style: 'Formal',
    price: 720,
    retailer: 'Ralph Lauren Black Label',
    imageUrl: heroImg,
    productUrl: 'https://example.com/ralph-lauren-tuxedo',
  },
  {
    id: 'prod-07',
    name: 'Heavyweight Supima Cotton Tee',
    category: 'Tops',
    style: 'Casual',
    price: 75,
    retailer: 'Auralee Tokyo',
    imageUrl: outfitStreetImg,
    productUrl: 'https://example.com/auralee-supima-tee',
  },
  {
    id: 'prod-08',
    name: 'Square-Toe Calfskin Chelsea Boot',
    category: 'Footwear',
    style: 'Minimalist',
    price: 250,
    retailer: 'Totême Form',
    imageUrl: outfitSmartImg,
    productUrl: 'https://example.com/toteme-chelsea-boot',
  },
  {
    id: 'prod-09',
    name: 'Garment-Dyed Relaxed Linen Shirt',
    category: 'Tops',
    style: 'Casual',
    price: 125,
    retailer: 'Norse Projects',
    imageUrl: outfitSmartImg,
    productUrl: 'https://example.com/norse-linen-shirt',
  },
  {
    id: 'prod-10',
    name: 'Minimalist Leather Day Pack',
    category: 'Accessories',
    style: 'Minimalist',
    price: 195,
    retailer: 'Building Block Studio',
    imageUrl: outfitStreetImg,
    productUrl: 'https://example.com/building-block-bag',
  },
  {
    id: 'prod-11',
    name: 'Asymmetrical Raw Matka Silk Kurta',
    category: 'Tops',
    style: 'Ethnic',
    price: 280,
    retailer: 'Antar-Agni Studio',
    imageUrl: heroImg,
    productUrl: 'https://example.com/antar-agni-kurta',
    isNewArrival: true,
  },
  {
    id: 'prod-12',
    name: 'Bespoke Barathea Evening Trouser',
    category: 'Trousers',
    style: 'Formal',
    price: 160,
    retailer: 'Savitri Bespoke',
    imageUrl: heroImg,
    productUrl: 'https://example.com/savitri-evening-trouser',
  },
];
